### ISSUE TITLE
Missing dependances

### ISSUE THREAD

**Issue by TrikzMe** [paulsapps/msgi#22]
Hi,
I'm trying to compile your project but somme artifacts are missing even the buildbot show a success

Can you please inject what is missing?
Thank you a lot for your work and support!
I hope I'll be able to make it work!
Have a nice day.

**Comment by MrSapps** [comment]
Hi - can you post your build log/failure? AFAIK everything it requires should be included

**Comment by TrikzMe** [comment]
Thank you for answer, here is the logs:

> Build started
> git clone -q --branch=master https://github.com/paulsapps/msgi.git C:\projects\msgi-kvntc
> "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "Source\MSGI.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
> Microsoft (R) Build Engine version 12.0.40629.0
> [Microsoft .NET Framework, version 4.0.30319.42000]
> Copyright (C) Microsoft Corporation. All rights reserved.
>   modules.cpp
> c1xx : fatal error C1083: Cannot open source file: '....\3rdParty\Detours\src\modules.cpp': No such file or directory [C:\projects\msgi-kvntc\Source\DetoursLib\DetoursLib.vcxproj]
>   image.cpp
> c1xx : fatal error C1083: Cannot open source file: '....\3rdParty\Detours\src\image.cpp': No such file or directory [C:\projects\msgi-kvntc\Source\DetoursLib\DetoursLib.vcxproj]
>   disasm.cpp
> c1xx : fatal error C1083: Cannot open source file: '....\3rdParty\Detours\src\disasm.cpp': No such file or directory [C:\projects\msgi-kvntc\Source\DetoursLib\DetoursLib.vcxproj]
>   detours.cpp
> c1xx : fatal error C1083: Cannot open source file: '....\3rdParty\Detours\src\detours.cpp': No such file or directory [C:\projects\msgi-kvntc\Source\DetoursLib\DetoursLib.vcxproj]
>   creatwth.cpp
> c1xx : fatal error C1083: Cannot open source file: '....\3rdParty\Detours\src\creatwth.cpp': No such file or directory [C:\projects\msgi-kvntc\Source\DetoursLib\DetoursLib.vcxproj]
>   Generating Code...
>   gmock-all.cc
> c1xx : fatal error C1083: Cannot open source file: '....\3rdParty\gmock-1.7.0\src\gmock-all.cc': No such file or directory [C:\projects\msgi-kvntc\Source\gmock\gmock.vcxproj]
>   gtest-all.cc
> c1xx : fatal error C1083: Cannot open source file: '....\3rdParty\gmock-1.7.0\gtest\src\gtest-all.cc': No such file or directory [C:\projects\msgi-kvntc\Source\gmock\gmock.vcxproj]
>   Generating Code...
> Command exited with code 1

Screenshot version:
[http://www.turbopix.fr/i/eh7QtTrJTZ.jpg](url)

**Comment by MrSapps** [comment]
You need to pass the --recursive option to git clone so that it pulls down the submodules

**Comment by TrikzMe** [comment]
Thank you!
This is compiled now :)
Is there any docs to use it?

I placed files on mgs main MGS I dir then try to launch by MgsExe.exe -c or MgsExe.exe -w but it crashs (I'm on windows 7 x64)
Tests.exe show me passed tests:

> C:\Users\%username%>"C:\Program Files (x86)\Metal Gear Solid\Tests.exe"
> [==========] Running 2 tests from 2 test cases.
> [----------] Global test environment set-up.
> [----------] 1 test from Task
> [ RUN      ] Task.Init
> [       OK ] Task.Init (16 ms)
> [----------] 1 test from Task (16 ms total)
> 
> [----------] 1 test from Sound
> [ RUN      ] Sound.Sound_HexCharToInt
> [       OK ] Sound.Sound_HexCharToInt (0 ms)
> [----------] 1 test from Sound (0 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 2 tests from 2 test cases ran. (16 ms total)
> [  PASSED  ] 2 tests.
> 
>   YOU HAVE 2 DISABLED TESTS

I'm really exited about it! :D

**Comment by MrSapps** [comment]
It compiles to a dll that the game loads, it might crash because some functions are not yet correct. You'd have to debug. It will take lots more debugging to ensure that current stuff is correct and to implement the other 100's of missing functions.

**Comment by TrikzMe** [comment]
Oh ok, thanks for infos.
I wich you luck! :)
